# Secrets (to be encrypted with Ansible Vault)
keycloak_admin_password: "admin"
payara_admin_password: "admin"
postgresql_admin_password: "StrongAdminPassword123!"
postgresql_adr_keycloak_password: "StrongKeycloakPassword123!"
postgresql_adr_customer_password: "StrongAdrCustomerPassword123!"
