---
- name: Set backup directory fact
  ansible.builtin.set_fact:
    postgresql_backup_dir: "C:\\adr-backup-{{ apcm_version }}"

- name: Ensure backup directory exists (Windows)
  ansible.windows.win_file:
    path: "{{ postgresql_backup_dir }}"
    state: directory

- name: Perform PostgreSQL Backup (Windows)
  ansible.windows.win_shell: |
    $env:PGPASSWORD = "{{ postgresql_admin_password }}"
    & "{{ postgresql_bin_path_windows }}\pg_dump.exe" -U "{{ postgresql_admin_user }}" -f "{{ postgresql_backup_dir }}\{{ item }}.sql" "{{ item }}"
  loop:
    - "{{ postgresql_adr_db_name }}"
    - "{{ postgresql_keycloak_db_name }}"
  no_log: true
