---
- name: Setup PostgreSQL facts
  ansible.builtin.include_tasks: setup.yml
  tags: [always]

- name: Include Linux backup tasks
  ansible.builtin.include_tasks: backup_linux.yml
  when: ansible_facts['os_family'] != 'Windows'

- name: Include Windows backup tasks
  ansible.builtin.include_tasks: backup_windows.yml
  when: ansible_facts['os_family'] == 'Windows'
