---
- name: Stop PostgreSQL
  ansible.builtin.include_tasks: stop.yml
  when: not (postgresql_rds_enabled | default(false))

- name: Backup PostgreSQL
  ansible.builtin.include_tasks: backup.yml
  tags: [backup]

- name: Update PostgreSQL
  ansible.builtin.include_tasks: main.yml

- name: Start PostgreSQL
  ansible.builtin.include_tasks: start.yml
  when: not (postgresql_rds_enabled | default(false))
