---
- name: Install PostgreSQL (Windows)
  block:
    - name: Ensure PostgreSQL install directory exists
      ansible.windows.win_file:
        path: 'C:\adr\PostgreSQL'
        state: directory

    - name: Copy PostgreSQL installer to target
      ansible.windows.win_copy:
        src: "{{ artifacts.postgresql_windows.url }}"
        dest: "{{ ansible_facts['env']['TEMP'] }}\\{{ artifacts.postgresql_windows.name }}"

    - name: Install PostgreSQL via EXE
      ansible.windows.win_package:
        path: "{{ ansible_facts['env']['TEMP'] }}\\{{ artifacts.postgresql_windows.name }}"
        state: present
        arguments:
          - --mode
          - unattended
          - --unattendedmodeui
          - none
          - --prefix
          - 'C:\Program Files\PostgreSQL\{{ postgresql_version }}'
          - --datadir
          - "{{ postgresql_data_path_windows }}"
          - --superpassword
          - "{{ postgresql_admin_password }}"
          - --serverport
          - "5432"
          - --locale
          - "{{ postgresql_windows_collation }}"

    - name: Add PostgreSQL bin to PATH
      ansible.windows.win_path:
        elements: "{{ postgresql_bin_path_windows }}"
        state: present

    - name: Ensure PostgreSQL service is started (Windows)
      ansible.windows.win_service:
        name: "postgresql-x64-{{ postgresql_version }}"
        state: started
        start_mode: auto

    - name: Allow remote connections in postgresql.conf (Windows)
      ansible.windows.win_lineinfile:
        path: "{{ postgresql_data_path_windows }}\\postgresql.conf"
        regexp: "^#?listen_addresses\\s*="
        line: "listen_addresses = '*'"
      notify: Restart PostgreSQL

    - name: Allow remote connections in pg_hba.conf (Windows)
      ansible.windows.win_lineinfile:
        path: "{{ postgresql_data_path_windows }}\\pg_hba.conf"
        line: "host    all             all             {{ allowed_network_range }}               md5"
        insertafter: EOF
      notify: Restart PostgreSQL

