---
- name: Configure Payara
  hosts: all
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  tasks:
    - name: Run Payara configuration tasks
      ansible.builtin.include_role:
        name: payara
        tasks_from: config
      tags: [payara, config]
    - name: Cleanup temporary files
      ansible.builtin.include_role:
        name: cleanup
      tags: [payara, config]
