---
- name: Configure Nginx
  hosts: all
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  tasks:
    - name: Run Nginx configuration tasks
      ansible.builtin.include_role:
        name: nginx
        tasks_from: config
      when: "'backend_servers' not in group_names"
      tags: [nginx, config]
    - name: Cleanup temporary files
      ansible.builtin.include_role:
        name: cleanup
      tags: [nginx, config]
