---
- name: Deploy Common Infrastructure
  hosts: all
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  roles:
    - common
    # - postfix ### issues with logsize when not configured
    - zabbix

- name: Deploy Databases
  hosts: "{{ 'all' if (mongodb_host == 'localhost' and not (postgresql_rds_enabled | default(false))) else mongodb_host }}"
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  roles:
    - mongodb
    - postgresql

- name: Deploy Keycloak
  hosts: "{{ 'frontend_servers' if keycloak_host != 'localhost' else 'all' }}"
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  roles:
    - keycloak

- name: Deploy Application and Proxy
  hosts: "{{ 'all' if (keycloak_host == 'localhost' and backend_payara_host == 'localhost') else keycloak_host ~ ':' ~ backend_payara_host }}"
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  roles:
    - payara
    - role: nginx
      when: "'backend_servers' not in group_names"

- name: Cleanup and Summary
  hosts: all
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"
  post_tasks:
    - name: Display PostgreSQL Credentials
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Super Admin: {{ postgresql_admin_user }} / {{ postgresql_admin_password }}"
          - "PostgreSQL Keycloak User: adr_keycloak_user / {{ postgresql_adr_keycloak_password }}"
          - "PostgreSQL Keycloak Database: adr_keycloak_{{ customer_name }} / {{ postgresql_adr_keycloak_password }}"
          - "PostgreSQL ADR Customer User: adr_{{ customer_name }} / {{ postgresql_adr_customer_password }}"
          - "PostgreSQL ADR Customer Database: adr_{{ customer_name }} / {{ postgresql_adr_customer_password }}"
      when:
        - postgresql_admin_user is defined
        - postgresql_admin_password is defined

    - name: Cleanup temporary files
      ansible.builtin.include_role:
        name: cleanup
