---
- name: Update Keycloak
  hosts: all
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all_secrets.yml
    - "../{{ include_release_vars | default('vars/releases/4.0.9.yml') }}"

  tasks:
    - name: Run Keycloak update tasks
      ansible.builtin.include_role:
        name: keycloak
        tasks_from: update

    - name: Cleanup temporary files
      ansible.builtin.include_role:
        name: cleanup
