---
- name: Download Payara bundle
  ansible.builtin.include_role:
    name: integrity
  vars:
    integrity_artifact_url: "{{ artifacts.get('payara', {}).get('url', '') }}"
    integrity_artifact_dest: "{{ payara_bundle_dest | default('') }}"
    integrity_artifact_checksum: "{{ artifacts.get('payara', {}).get('checksum', '') }}"
    integrity_validate_certs: "{{ artifacts.get('payara', {}).get('validate_certs', true) }}"
    integrity_force_os: "{{ ansible_facts.get('os_family', 'Linux') }}"
  when: artifacts is defined and artifacts.get('payara') is defined

- name: Create versioned directory (Linux)
  ansible.builtin.file:
    path: "{{ payara_extract_path }}"
    state: directory
    mode: '0755'

- name: Extract Payara bundle (Linux)
  ansible.builtin.unarchive:
    src: "{{ payara_bundle_dest }}"
    dest: "{{ payara_extract_path }}"
    remote_src: true

- name: Ensure shell scripts are executable (Linux)
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
  loop: "{{ query('ansible.builtin.fileglob', payara_actual_path + '/*.sh') }}"

- name: Create profiles/ansible directory
  ansible.builtin.file:
    path: "{{ payara_actual_path }}{{ payara_sep }}profiles{{ payara_sep }}ansible"
    state: directory
    mode: '0755'

- name: Template config.properties
  ansible.builtin.template:
    src: config.properties.j2
    dest: "{{ payara_actual_path }}{{ payara_sep }}profiles{{ payara_sep }}ansible{{ payara_sep }}config.properties"
    mode: '0644'

- name: Run prepare-config.sh (Linux)
  ansible.builtin.command:
    cmd: "./prepare-config.sh ansible"
    chdir: "{{ payara_actual_path }}"
  environment:
    JAVA_HOME: "{{ payara_java_home | default(common_java_home) | default('') }}"
    PATH: "{{ payara_java_home | default(common_java_home) | default('') }}/bin:{{ ansible_facts['env']['PATH'] }}"
  changed_when: true

- name: Create Payara symbolic link (Linux)
  ansible.builtin.file:
    src: "{{ payara_actual_path }}{{ payara_sep }}payara5"
    dest: "{{ payara_symlink_path }}"
    state: link
    force: true

- name: Find mandatory scripts
  ansible.builtin.find:
    paths: "{{ payara_actual_path }}"
    patterns: "[1-9]*-payara--*.sh"
  register: payara_mandatory_scripts

# - name: Run mandatory scripts (Linux)
#   ansible.builtin.command:
#     cmd: "./{{ item.path | basename }}"
#     chdir: "{{ payara_actual_path }}"
#   environment:
#     JAVA_HOME: "{{ common_java_home | default('') }}"
#     PATH: "{{ common_java_home | default('') }}/bin:{{ ansible_facts['env']['PATH'] }}"
#   loop: "{{ payara_mandatory_scripts.files | sort(attribute='path') }}"
#   changed_when: true

- name: Verify Payara extraction
  ansible.builtin.stat:
    path: "{{ payara_actual_path }}/payara5"
  register: payara_verify_stat

- name: Assert Payara is present
  ansible.builtin.assert:
    that:
      - payara_verify_stat.stat.exists
    msg: "Payara server not found at {{ payara_actual_path }}/payara5"
