#
# Copyright (c) 2024 Ampacimon S.A.,
# Rue Alfred Deponthière 40, B4431 Loncin, Belgium
# All rights reserved.
#
# This software is the confidential and proprietary information
# of Ampacimon S.A. ("Confidential Information").
# You SHALL NOT disclose such Confidential Information and SHALL ONLY use
# or redistribute it in source or binary forms in accordance with the
# terms of the license agreement you entered into with Ampacimon S.A.
#

# Keycloak server host full name (use by internal services to address /auth)
keycloak.host.fqdn=localhost
# WARNING: should be the same in keycloak and NGINX bundle!
keycloak.https.port=8543
keycloak.https.managementport=9000

# Backend properties (identical to front properties if single-domain)
adr.server.host.fqdn=localhost
# WARNING: should be the same in Payara and NGINX bundle!
adr.server.https.port=8181

# Fully qualified name for accessing the front end used for keycloak realm generation  (eg. corellia.ampanet)
# WARNING: should be the same in Payara and NGINX bundle!
adr.front.host.fqdn=localhost
# Default for single-domain (= same as back-end) = 8181
# WARNING: should be the same in Payara, NGINX bundle!
adr.front.https.port=8181

# Fully qualified name for accessing the facility-ratings front end (eg. corellia.ampanet)
# let the default for setup without FR
# WARNING: should be the same in Facility and NGINX bundle!
facility.front.host.fqdn=localhost
# WARNING: should be the same in Facility and NGINX bundle!
facility.front.https.port=4949

#  In order of preference:
#   - External DNS hostname (eg. access from Internet - extranet.ampacimon.com) or
#   - Proxy host address if any
#   - localhost 
#  WARNING: should be the same in Payara, Keycloak and NGINX bundle!
ext.host.fqdn=localhost

# Where the static files are deployed (landing page, errors, favicon)
#for windows use forward /
#static.files.folder=/var/www/ampacimon
static.files.folder=c:/adr/apcm-nginx-bundle/nginx/static

# Where nginx is installed
#for windows use forward /
#nginx.home.directory=/etc/nginx
nginx.home.directory=c:/adr/apcm-nginx-bundle/nginx
#for windows use forward /
#nginx.log.directory=/var/log/nginx
nginx.log.directory=c:/adr/apcm-nginx-bundle/nginx/logs

#ADR public rest api limit (in r/s or r/m aka request per sec/min per ip)
adr.api.rest.limit=20r/m
#ADR rest api burst limit
adr.api.burst=20

#All api/html limit (in r/s or r/m aka request per sec/min per ip)
nginx.api.global.limit=100r/s

#Set what to do if the connecting ip is unknown (must be escaped)
#typical values are :
# (empty)  - no ip filtering (on prem)
# "deny\ all\;" - lock any unknown ip
#it can be updated after install per access list by editing nginx/xxx-shared/xxx-access.conf
nginx.unknown.ip.behavior=deny\ all\;

#MUI : define what access list to use, possible values are "admin", "app" (app for anyone that can use the base app)
nginx.mui.access=admin

#publish or hide /auth/realms/apcm-realm/.well-known/openid-configuration, should be false if no external integration is made
keycloak.publish.wellknown=false

#where do you land if you go to /
#typical values
#/index.html
#/adr/
#/facility-ratings/
nginx.root.path=/index.html
#------------------------------------------------------------------------------#
#                             log data directories                             #
#------------------------------------------------------------------------------#
# The root directory must be specified.                                        #
# WARNING: Escape the \ character twice all the time!                          #
# Example.1: \\\\\\\\BELGRID.net\\\\data                                       #
# Example.2: /tmp/adr  -> works on linux and windows (=> C:\tmp\adr)         #
# user and password are only required for Windows under specific setup         #
# Mandatory if the network folder is user/password protected.                  #
# Leave user and password empty if not requiered                               #
#------------------------------------------------------------------------------#
nginx.datadir=ChangeMe
nginx.datadir.user=ChangeMe
nginx.datadir.password=ChangeMe

#for servers with multiple nginx configurations a custom name can be used to avoid name conflicts in autogenerated files
nginx.config.name=ampacimon
