---
- name: Set backup directory fact
  ansible.builtin.set_fact:
    mongodb_backup_dir: "C:\\adr-backup-{{ apcm_version }}"

- name: Ensure backup directory exists (Windows)
  ansible.windows.win_file:
    path: "{{ mongodb_backup_dir }}"
    state: directory

- name: Perform MongoDB Backup (Windows)
  ansible.windows.win_shell: |
    & "C:\adr\MongoDB\bin\mongodump.exe" --port 27017 --username {{ mongodb_admin_user }} --password {{ mongodb_admin_password }} --authenticationDatabase admin --out "{{ mongodb_backup_dir }}\mongodb-backup"
  no_log: true
