---
- name: Set facts for Keycloak
  ansible.builtin.set_fact:
    keycloak_symlink_path: "{{ (ansible_facts['os_family'] == 'Windows') | ternary(keycloak_symlink_path_windows, keycloak_symlink_path_linux) }}"
    keycloak_service_name: "{{ (ansible_facts['os_family'] == 'Windows') | ternary('Keycloak', keycloak_service_name_linux) }}"
    keycloak_base_path: "{{ (ansible_facts['os_family'] == 'Windows') | ternary(adr_base_path_windows, adr_base_path_linux) }}"
    keycloak_sep: '{{ (ansible_facts["os_family"] == "Windows") | ternary("\\", "/") }}'
    keycloak_artifact: "{{ (keycloak_flavor == 'rh') | ternary(artifacts.get('keycloak_rh', artifacts.get('keycloak', {})), artifacts.get('keycloak_standard', artifacts.get('keycloak', {}))) | default({}) }}"
  tags: [always]

- name: Set path facts for Keycloak
  ansible.builtin.set_fact:
    keycloak_bundle_dest: "{{ keycloak_base_path }}{{ keycloak_sep }}{{ keycloak_artifact.get('name', '') }}"
    keycloak_version_dir: "{{ keycloak_artifact.get('name', '') | regex_replace('\\.zip$', '') }}"
  when: keycloak_artifact and keycloak_artifact.get('name')
  tags: [always]

- name: Set extraction path facts for Keycloak
  ansible.builtin.set_fact:
    keycloak_extract_path: "{{ keycloak_base_path }}{{ keycloak_sep }}{{ keycloak_version_dir }}"
  when: keycloak_artifact and keycloak_artifact.get('name')
  tags: [always]

- name: Set Linux specific path facts for Keycloak
  ansible.builtin.set_fact:
    keycloak_actual_path: "{{ keycloak_extract_path }}{{ keycloak_sep }}{{ keycloak_extract_dir }}"
  when: ansible_facts['os_family'] != 'Windows'
  tags: [always]
