all:
  children:
    linux:
      vars:
        ansible_become: true
      hosts:
        linux-server-01:
          ansible_host: 127.0.0.1
    windows:
      vars:
        ansible_become: false
      hosts:
        windows-server-01:
          ansible_host: 127.0.0.1
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
    local:
      hosts:
        localhost:
          ansible_connection: local
