---
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ (ansible_facts['os_family'] == 'Windows') | ternary('postgresql-x64-' + postgresql_version, 'postgresql') }}"
    state: restarted
